### PR TITLE
Semver

### PR DESCRIPTION
**Pull request by Kidev**

### CODE REVIEW

**Comment by christoph-nimagna** [comment]
@Kidev - First of all: Thank you very much for working on a fix for this issue! ❤️ 

I saw your comment above and tried your fix with the suggested setting of `aqtsource` using:
```
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.8.0"
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        dir: 'C:\'
        install-deps: 'true'
        modules: 'qtimageformats qtmultimedia qtpositioning qtpdf'
        cache: 'false'
        setup-python: 'true'
        set-env: 'true'
        tools-only: 'false'
        # TEMPORARY FIX ONLY UNTIL https://github.com/miurahr/aqtinstall/pull/839 and https://github.com/jurplel/install-qt-action/issues/260 are resolved
        aqtsource: 'git+https://github.com/Kidev/aqtinstall.git'
```
but it failed to get `QtPdf` with the following output
```
Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (65.5.0)
Collecting wheel
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
[...]
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m pip install git+https://github.com/Kidev/aqtinstall.git
Collecting git+https://github.com/Kidev/aqtinstall.git
  Cloning https://github.com/Kidev/aqtinstall.git to c:\users\runneradmin\appdata\local\temp\pip-req-build-f4lzsz4b
  Running command git clone --filter=blob:none --quiet https://github.com/Kidev/aqtinstall.git 'C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-f4lzsz4b'
  Resolved https://github.com/Kidev/aqtinstall.git to commit 6168fa847a76af30bb8db4902c04460b0f16592b
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
[...]
Successfully built aqtinstall patch
Installing collected packages: patch, urllib3, soupsieve, semantic-version, py7zr, idna, humanize, defusedxml, charset-normalizer, certifi, requests, beautifulsoup4, bs4, aqtinstall
  Attempting uninstall: py7zr
    Found existing installation: py7zr 0.20.8
    Uninstalling py7zr-0.20.8:
      Successfully uninstalled py7zr-0.20.8
Successfully installed aqtinstall-0.1.dev1809 beautifulsoup4-4.12.3 bs4-0.0.2 certifi-2024.8.30 charset-normalizer-3.4.0 defusedxml-0.7.1 humanize-4.11.0 idna-3.10 patch-1.16 py7zr-1.0.0rc1 requests-2.32.3 semantic-version-2.10.0 soupsieve-2.6 urllib3-2.2.3
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m aqt version
INFO    : aqtinstall(aqt) v0.1.dev1809 on Python 3.11.9 [CPython MSC v.1[93](https://github.com/NimagnaAG/Nimagna-App/actions/runs/12076534056/job/33678220245#step:9:97)8 64 bit (AMD64)]
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m aqt install-qt windows desktop 6.8.0 win64_msvc2022_64 --outputdir C:\/Qt --modules qtimageformats qtmultimedia qtpositioning qtpdf
INFO    : aqtinstall(aqt) v0.1.dev1809 on Python 3.11.9 [CPython MSC v.1938 64 bit (AMD64)]
ERROR   : The packages ['qtpdf'] were not found while parsing XML of package information!
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt windows desktop --modules 6.8.0 <arch>' to show modules available.
Error: Error: The process 'C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe' failed with exit code 1
```

Can you help me with that?

**Comment by Kidev** [comment]
I think there is an issue, I can't get some modules on my CI yet. Try with `modules: 'all'` maybe? But since its not a regular module it may not work. In 6.7.3 it should though. I'm still figuring this out

**Comment by Kidev** [comment]
@christoph-nimagna Oh not I get ! My fix for qtpdf (since its no longer a module it's an extension) is only available on the semver branch. Try this for aqtsource:
`aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@semver'`

Hope this helps

**Comment by Kidev** [comment]
I'm using this PR to be able to run the aqt CI btw, it just fails because some error messages are not the one expected that's all

**Comment by christoph-nimagna** [comment]
@Kidev - thanks for the repsonse. Using the suggested `aqtsource` value fixed the issue with fetching Qt 6.8.0. 

However, later in our build script (using CMake on a Visual Studio build), it fails with

```
CMake Error at InputOutput/CMakeLists.txt:161 (find_package):
  Found package configuration file:

    C:/Qt/6.8.0/msvc2022_64/lib/cmake/Qt6/Qt6Config.cmake
-- Configuring incomplete, errors occurred!

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find required Qt component "Pdf".

  Expected Config file at
  "C:/Qt/6.8.0/msvc2022_64/lib/cmake/Qt6Pdf/Qt6PdfConfig.cmake" does NOT
  exist
```

When listing the contents of the `C:/Qt/6.8.0/msvc2022_64/lib/cmake` folder, the `Qt6Pdf` folder is missing indeed:

```
[...]
lib\cmake\Qt6Linguist
lib\cmake\Qt6LinguistTools
lib\cmake\Qt6Multimedia
lib\cmake\Qt6MultimediaQuickPrivate
lib\cmake\Qt6MultimediaWidgets
lib\cmake\Qt6Network
lib\cmake\Qt6OpenGL
lib\cmake\Qt6OpenGLWidgets
lib\cmake\Qt6PacketProtocolPrivate
lib\cmake\Qt6PngPrivate
lib\cmake\Qt6Positioning
lib\cmake\Qt6PositioningQuick
lib\cmake\Qt6PrintSupport
lib\cmake\Qt6QDocCatchConversionsPrivate
lib\cmake\Qt6QDocCatchGeneratorsPrivate
lib\cmake\Qt6QDocCatchPrivate
lib\cmake\Qt6Qml
[...]
```

So, something must be missing in your fix to install the QtPdf extension correctly...

**Comment by Kidev** [comment]
@christoph-nimagna Ok so I must have messed up something somewhere. I created /semver2 that does not contain any style "fixes". For me it works:
```shell
$ aqt install-qt windows desktop 6.8.0 win64_msvc2022_64 --modules qtpdf
$ ll 6.8.0/msvc2022_64/lib
...
.rw-r--r--  6.7M kidev  2 Oct 05:38 ├── Qt6OpenGLd.lib
.rw-r--r--    86 kidev  3 Dec 20:18 ├── Qt6OpenGLd.prl
.rw-r--r--   17k kidev  2 Oct 05:40 ├── Qt6OpenGLWidgets.lib
.rw-r--r--    92 kidev  3 Dec 20:18 ├── Qt6OpenGLWidgets.prl
.rw-r--r--   17k kidev  2 Oct 05:40 ├── Qt6OpenGLWidgetsd.lib
.rw-r--r--    93 kidev  3 Dec 20:18 ├── Qt6OpenGLWidgetsd.prl
.rw-r--r--  1.2M kidev  2 Oct 12:36 ├── Qt6PacketProtocol.lib
.rw-r--r--   233 kidev  3 Dec 20:18 ├── Qt6PacketProtocol.prl
.rw-r--r--  1.5M kidev  2 Oct 12:36 ├── Qt6PacketProtocold.lib
.rw-r--r--   236 kidev  3 Dec 20:18 ├── Qt6PacketProtocold.prl
.rw-r--r--   81k kidev  2 Oct 20:34 ├── Qt6Pdf.lib
.rw-r--r--    82 kidev  3 Dec 20:18 ├── Qt6Pdf.prl
.rw-r--r--   82k kidev  2 Oct 20:34 ├── Qt6Pdfd.lib
.rw-r--r--    83 kidev  3 Dec 20:18 ├── Qt6Pdfd.prl
.rw-r--r--   63k kidev  2 Oct 20:35 ├── Qt6PdfQuick.lib
.rw-r--r--    87 kidev  3 Dec 20:18 ├── Qt6PdfQuick.prl
.rw-r--r--   63k kidev  2 Oct 20:35 ├── Qt6PdfQuickd.lib
.rw-r--r--    88 kidev  3 Dec 20:18 ├── Qt6PdfQuickd.prl
.rw-r--r--   25k kidev  2 Oct 20:35 ├── Qt6PdfWidgets.lib
.rw-r--r--    89 kidev  3 Dec 20:18 ├── Qt6PdfWidgets.prl
.rw-r--r--   25k kidev  2 Oct 20:35 ├── Qt6PdfWidgetsd.lib
.rw-r--r--    90 kidev  3 Dec 20:18 ├── Qt6PdfWidgetsd.prl
...
```

Use this format in the qt-install action:
```
aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@semver2'
```

**Comment by Kidev** [comment]
test

**Pull request closed without merging**
